### ISSUE TITLE
Linux client

### ISSUE THREAD

**Issue by ananthb** [vesvault/VESmail#1]
Can this be built and run on Linux?

**Comment by vesvault** [comment]
Sure. VESmail daemon built from this repo runs fine on Linux, the sample startup conf for systemd and xinetd are in etc/ subdir.
At the moment there's no GUI or SNIF version of VESmail for Linux, although it can be done similar to other apps.
Use https://my.vesmail.email/profile/?local=1 for localhost setup on Linux

**Comment by ananthb** [comment]
Great, I'll try it out. Why does it depend on automake 1.13 alone? Could it not depend on a minimum supported version?

**Comment by vesvault** [comment]
Good point, thanks for noticing. There was a little problem with the prebuilt Makefile.in, fixed in the latest rollout.

**Comment by ananthb** [comment]
Fantastic! Thanks 👍

**Comment by ananthb** [comment]
Do you want help packaging this and generating Linux builds? I can help out with that. Otherwise we can close this issue. Looks like Linux is supported after all.

**Comment by vesvault** [comment]
If you want to play with the Linux version - it would be really awesome!
Here's a test I was working with on Linux -
[https://vesmail.email/assets/download/VESmail-lo.tgz]
Place it in the app/ subdirectory of the VESmail repo to build.
It also refers [https://github.com/vesvault/snif-tunl] - a local ip terminator for SNIF, which is opportunistically started as a TUN/TAP.

**Comment by ananthb** [comment]
I will definitely try that out. I have to wrap my head around the configuration first to get it up and running. Should I unpack VESmail-lo and run make in that dir?

**Comment by vesvault** [comment]
Yes if you place it in app/ it should build from its own Makefile, it refers relative paths. It also refers snif-tunl, you may have to adjust the path to it.

**Comment by ananthb** [comment]
Where should snif-tunl be for this to work? I'm unable to figure out the right path for it.

**Comment by vesvault** [comment]
You may put the snif-tunl subdir inside of snif/tunl/ of the VESmail repo,
or adjust the include path and lib path in the Makefile to point to your snif-tunl location.
Before building VESmail-lo, build libsnifl.a in snif-tunl (recently updated).
As a matter of fact, snif-tunl is optional and can be removed at all from the Makefile, then the app will be accessible through localhost or SNIF relay without the tun/tap option.

**Comment by ananthb** [comment]
OK that is cool! It works over SNIF just like the Android app.

**Comment by ananthb** [comment]
These are the logs from VESmail-lo:

```
ananth@toolbox ~/s/V/a/VESmail-lo (master)> ./vesmail-lo 
s=0x1949f90
s=0x188d430
206.189.255.198
ioctl[TUNSETIFF]: Operation not permitted
https://my.vesmail.email/profile?snif=<my-snif-code>.vesmail.xyz&snifauth=1
```

Setup works correctly and I'm able to authenticate via SNIF and then use VESmail. Is the ioctl call failing because I'm not running the binary as root? I'm planning on running this under my user as a systemd user service. Will this be an issue?

**Comment by ananthb** [comment]
Also where does VESmail-lo store settings and configuration?

**Comment by vesvault** [comment]
The ioctl error apparently happens when vesmail-lo is trying to initialize tun/tap snif-tunl. To make it work, need to either run as a root, or play with special system permissions for the user.
But again, snif-tunl is optional, the app functions just fine without it through SNIF or localhost.
snif-tunl was designed for the iOS build and is critical there, but on Linux it's used for testing only.
And actually, SNIF is just a convoluted way of simplifying the email client setup by using trusted TLS and standard port numbers. You can always use localhost and 7143/7125 ports without TLS, but most email clients keep showing security warnings.
The VESmail_conf struct used by vesmail-lo is not loaded from an external file but is inlined in srv/local.c
The SNIF key and cert paths are inlined in the VESmail-lo test.c, and can be changed to something better, just make sure these files are writable by the process, at least the cert as it will be automatically renewed.
Also there's a writable log file path in VESmail_local_init(), you may use NULL for system logs, and VESmail_local_caBundle() in case if openssl doesn't pick the system trust root for some reason.

**Comment by ananthb** [comment]
It runs fine as a systemd user service. Looks like the certificate and key are simply stored in the current working directory along with a log file.

This works without a config file but regular vesmail failed without one. Why?

**Comment by vesvault** [comment]
The local app build uses the inlined conf in srv/local.c, while the CLI/daemon build relies on the conf file, /etc/vesmail/vesmail.conf or an alternate path with a --conf command line argument.
You may copy the sample conf from etc/ in the repo, and edit it if necessary.

**Comment by ananthb** [comment]
Got it thanks. So what's different between regular vesmail and vesmail-lo?

**Comment by vesvault** [comment]
The regular vesmail is a server-grade utility. It loads all settings from the conf file, can run as a CLI utility to encrypt/decrypt a specific email message, as a standalone imap/smtp proxy process or as a daemon that listens on ports to launch proxy processes. The proxy can load an alternative conf based on the SNI name for running multiple domains on a single server, and needs externally generated certs and keys to run TLS. All these options are configurable in the master conf, and in SNI conf for each domains.
The vesmail-lo is a consumer app build, it uses same logic as the published builds for Android, Windows and Apple. It doesn't have an external conf file, doesn't support SNI alternative confs, runs only in a daemon mode, and automatically manages TLS through SNIF.

**Comment by ananthb** [comment]
Perfect. That's exactly what i wanted. Any plans to move this to a separate repo?

**Comment by vesvault** [comment]
Sure. It just needs to be cleaned up first, as it was an experimental build for internal testing

**Comment by ananthb** [comment]
I'll keep an eye out for it. I'm open to more experimental builds too!

**Comment by ananthb** [comment]
@vesvault I just re-build vesmail-lo today and after trying to login, the vesvault page is stuck at "Connecting to your VESmail app via SNIF relay (attempt #4)...". Has something changed?

**Comment by vesvault** [comment]
@ananthb Nothing have changed, the SNIF server is running fine. Are you using the correct url that vesmail-lo prints to stdout? You may try to connect to the SNIF host (snif= parameter in the url), https on port 7183, to test the connection to vesmail-lo

**Comment by ananthb** [comment]
I'm not able to connect to my vesmail-lo via SNIF. Can I get more logs out of vesmail-lo?

**Comment by ananthb** [comment]
I get this in the response if I visit localhost:7180

```json
{
  "schema": "VES-1.0",
  "servers": [
    {
      "server": "ves-imap",
      "host": "localhost",
      "port": 7143,
      "proto": "tcp",
      "tls": {
        "persist": false,
        "level": "none"
      }
    },
    {
      "server": "ves-smtp",
      "host": "localhost",
      "port": 7125,
      "proto": "tcp",
      "tls": {
        "persist": false,
        "level": "none"
      }
    }
  ]
}
```

**Comment by vesvault** [comment]
If you're using a SNIF host that starts with rf2414...
I see the response on https 7183.
If you have a different SNIF link - send it to me directly at jz@vesvault.com and i'll check what might be wrong
